### ISSUE TITLE
Calc Twiss

### ISSUE THREAD

**Issue by fernandohds564** [lnls-fac/pyaccel#31]
The docstring of the calc_twiss function says nothing about the outputs it generates.
By the way, why does this function returns all those outputs and not only the twiss parameters, given that there are specific functions to get all the others?
@xresende, @afonsoharuo, @LuanaVilela.

**Comment by afonsoharuo** [comment]
Added returns to docstring.

The function returns results from intermediate calculations because they are not very lightweight and are needed in other applications, such as the virtual accelerator. The first returned value is the main one, and can be retrieved by
```
twiss, *_ = calc_twiss(accelerator)
```

**Comment by xresende** [comment]
If a structure that is needed for the calculation of Twiss is not passed as an argument to _calc_twiss_ [closed orbit for example] then _calc_twiss_ calculates it. It seems a waist to throw this structure away when _calc_twiss_ returns. It may happen that the invoking script may need one of the intermediate data latter. In this case, instead of first calculating that structure before _calc_twiss_, you still have the choice of receiving it from _calc_twiss_

**Comment by fernandohds564** [comment]
Ok, Guys. you've convinced me.
