### ISSUE TITLE
About find_indices

### ISSUE THREAD

**Issue by fernandohds564** [lnls-fac/pyaccel#34]
I was thinking about the _find_indices_ function and I've realized there is no sense in having a default value for the input _value_, because in pyaccel all elements of the lattice have all the attributes.

I also thought about modifying this function adding a new optional input: a function which takes 2 arguments, the first being the _lattice[i].attribute_name_ and the second the _value_ and returns a boolean. In other words, this function defines de comparison we will make inside _find_indices_. This way we could use this sintax 

    >>fun = lambda x,y: x[2] != y
    >>sext_idx = pyaccel.lattice.find_indices(lattice,'polynom_b',value=0.0,comparison=fun)

to get all the sextupoles in the ring. Or

    >>fun2=lambda x,y: x.startswith(y)
    >>markers_idx = pyaccel.lattice.find_indices(lattice,'fam_name',value='mi',comparison=fun2)

to get all the markers 'mia' and 'mib' of the lattice.

Well, one could argue that the same could be achieved with:

    >> sext_idx = [ i for i in range(len(lattice)) if lattice[i].polynom_b[2] != 0.0]
    >> markers_idx = [ i for i in range(len(lattice)) if lattice[i].fam_name.startswith('mi')]

which is simpler, and this function is useless. :(
What do you guys think, @xresende @afonsoharuo @LuanaVilela ?

**Comment by xresende** [comment]
I agree. I think the option of default _None_ for _value_ came from a frivolous copy-and-paste from the defunct _pyring_, where elements attributes were not just a mirror of the equivalent _trackcpp_ attributes but were created on the python layer and then could assume _None_ values.

As for the comparison function argument option, I think it is a great idea if you implement it, otherwise I am not so sure. :bowtie: Seriously, I think it would be very useful.

**Comment by fernandohds564** [comment]
done.
