### ISSUE TITLE
About set_attribute function

### ISSUE THREAD

**Issue by fernandohds564** [lnls-fac/pyaccel#36]
The _set_attribute_ function cannot set elements of polynom_b or of any other array attribute of an Element object. Maybe we could add the optional parameters _m_ and _n_ from the _get_attribute_ function. What do you think?

I also noticed this function changes the input parameter _lattice_ in place, what makes unnecessary to return it after the operation. Is this what we really want or we want to make a copy of _lattice_, change this copy and then return it as output?
@xresende @afonsoharuo @LuanaVilela

**Comment by xresende** [comment]
@fernandohds564, **the second part of the issue you raised**:

I think _set_attribute_ returns a reference to the modified input lattice to allow for the same syntax as AT. (copy-paste of existing code from Matlab to python would be one bit easier to adapt). But by returning a reference to the modified lattice it may mislead the user of the function or raise doubts.    

To me now it seems more appropriate to give up trying to keep the syntax of _pyaccel_ as close as possible to _AT_. The ways the two languages implement variable storage are too different for that purpose. We would only end up with either inconsistencies in the API of _pyaccel_ or inefficiencies in the implementation of the library. And for _set_attribute_ to return a modified copy of the original lattice so that we could keep the same syntax as _setcellstruct_ it would force us to introduce a computation and memory overhead while creating a new copy of the lattice that is not justifiable in all cases where _set_attribute_ is invoked. In those cases where we actually want to generate a new modified copy, we could always create an identical copy first and pass it to _set_attribute_.

I think we should modify _set_attribute_ so that it does not return anything.
 
**first part**

I though this problem with setting _polynom_a_ or _polynom_b_, which we had in the paste, was already solved. Maybe not for all possible invocation syntaxes... maybe you can provide us with your example.
As for _M_, _N_ arguments, I think it is useful and should be implemented. We just did not have time yet to do it for _set_attribute_, as we did for _get_attribute_

**Comment by fernandohds564** [comment]
** @xresende, the second part of your comment, or the first part of the issue:**
Only to clarify my initial point, what I meant was we cannot set *acc[i].polynom_b[2]*, for example, with the current version of *set_attribute*. I did not mean there is a bug in the code, where we try to set an argument and it does not change its value. I will implement the *m* and *n* inputs.

**The first, related to the second**:  I completely agree.
